apiVersion: apps/v1
kind: Deployment
metadata:
  name: akscalculator 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akscalculator
  template:
    metadata:
      labels:
        app: akscalculator 
    spec:
      containers:
        - name: akscalculator
          image: mondevappsharedcr.azurecr.io/akscalculator:v1
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: "1G"
            limits:
              cpu: 500m
              memory: "2G"
          env:
          - name: AZP_AGENT_NAME
            value: ncs-jmeter-__NCSAzureDevOpsAgentsJMeterTag__-agent-1
          - name: AZP_POOL
            value: 'my-new-pool'
          - name: AZP_TOKEN
            valueFrom: 
              secretKeyRef:
                name: mon-azuredevops-pat-token
                key: pattokensecret
          - name: AZP_URL
            value: __AzureDevOpsUrl__
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
    name: akscalculator
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: akscalculator
