apiVersion: apps/v1
kind: Deployment
metadata:
  name: akscalculator 
spec:
  replicas: 2
  progressDeadlineSeconds: 1800
  selector:
    matchLabels:
      app: akscalculator
  template:
    metadata:
      labels:
        app: akscalculator 
    spec:
      containers:
        - name: akscalculator
          image: mondevappsharedcr.azurecr.io/akscalculator:v1
          ports:
          - containerPort: 80
          env:
          - name: AZP_POOL
            value: 'my-new-pool'
          - name: AZP_TOKEN
            valueFrom: 
              secretKeyRef:
                name: mon-azuredevops-pat-token
                key: pattokensecret
          - name: AZP_URL
            value: __AzureDevOpsUrl__
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
    name: akscalculator
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: akscalculator
